version: '3.3' 
services:
  blazegraph:
    image: openkbs/blazegraph-docker
    container_name: blazegraph-docker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_ID=${USER_ID:-1001}
      - GROUP_ID=${GROUP_ID:-1001}
      - JVM_MEM=2g
    env_file:
      - ./.env
    ports:
      - 9999:9999
    volumes:
      ## Blazegraph data store
      - type: volume
        source: blazegraph_data
        target: /var/lib/blazegraph/data
        read_only: false
      - $PWD/workspace:/home/developer/workspace
      - $PWD/data:/home/developer/data 
      #- $PWD/conf:/usr/blazegraph/conf
      - $PWD/.java:/home/developer/.java 
      - $PWD/.profile:/.profile
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 3s
      timeout: 5s
      retries: 3
  
volumes:
  blazegraph_data:


